# Generated by Django 5.2.7 on 2025-11-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authusers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
