# Generated by Django 5.2.7 on 2025-10-22 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RestaurantSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_accepting_orders", models.BooleanField(default=True)),
                ("min_ready_minutes", models.PositiveIntegerField(default=10)),
                ("max_ready_minutes", models.PositiveIntegerField(default=75)),
                ("default_ready_minutes", models.PositiveIntegerField(default=20)),
                ("open_time", models.TimeField(default=datetime.time(11, 30))),
                ("close_time", models.TimeField(default=datetime.time(21, 30))),
            ],
            options={
                "verbose_name": "Restaurant Setting",
                "verbose_name_plural": "Restaurant Settings",
            },
        ),
    ]
