# Generated by Django 5.2.7 on 2025-10-19 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Allergen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name": "Allergen",
                "verbose_name_plural": "Allergens",
                "db_table": "allergen",
            },
        ),
        migrations.CreateModel(
            name="MenuCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("sort_order", models.SmallIntegerField(unique=True)),
            ],
            options={
                "verbose_name": "Menu Category",
                "verbose_name_plural": "Menu Categories",
                "db_table": "menu_category",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ItemAllergen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allergen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_allergens",
                        to="menu.allergen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Allergen",
                "verbose_name_plural": "Item Allergens",
                "db_table": "item_allergen",
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("description", models.CharField(max_length=300)),
                ("is_available", models.BooleanField(default=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "allergens",
                    models.ManyToManyField(
                        related_name="menu_items",
                        through="menu.ItemAllergen",
                        to="menu.allergen",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="menu.menucategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Item",
                "verbose_name_plural": "Menu Items",
                "db_table": "menu_item",
                "unique_together": {("name", "category")},
            },
        ),
        migrations.AddField(
            model_name="itemallergen",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_allergens",
                to="menu.menuitem",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="itemallergen",
            unique_together={("item", "allergen")},
        ),
    ]
