# Generated by Django 5.2.7 on 2025-10-20 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemallergen",
            name="allergen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allergen",
                to="menu.allergen",
            ),
        ),
        migrations.AlterField(
            model_name="itemallergen",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item",
                to="menu.menuitem",
            ),
        ),
    ]
