# Generated by Django 5.2.7 on 2025-11-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_alter_menuitem_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="menu_images/"
            ),
        ),
    ]
